version: '3'

services:
  auth_mysql:
    image: mysql:8.0
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --default-authentication-plugin=mysql_native_password]
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
    environment:
      - MYSQL_ROOT_PASSWORD=${AA_DB_ROOT_PASSWORD?err}
    healthcheck:
      test: ["CMD", "mysqladmin", "-uroot", "-proot", "-h", "localhost", "ping"]
      interval: 5s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - allianceauth

  nginx:
    image: nginx:1.21
    restart: always
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - static-volume:/var/www/myauth/static
    depends_on:
      - allianceauth
    labels:
      - traefik.enable=true
      - traefik.http.routers.auth.rule=Host(`auth.black-rose.space`)
      - traefik.http.routers.auth.entrypoints=websecure
      - traefik.http.routers.auth.tls.certresolver=primary
    networks:
      - traefik
      - allianceauth

  mumble_auth:
    container_name: ${MUMBLE_HOST_NAME}
    hostname: ${MUMBLE_HOST_NAME}
    build:
      context: .
      dockerfile: mumble.dockerfile
    env_file:
      - ./.env
    restart: unless-stopped
    volumes:
      - mumble-data:/data
      - /etc/letsencrypt:/etc/letsencrypt:ro    
    depends_on:
      - auth_mysql
    networks:
      - allianceauth
      - traefik
    labels:
      - traefik.enable=true
      - traefik.udp.routers.mumble.entrypoints=mumble_udp
      - traefik.udp.routers.mumble.service=mumble
      - traefik.udp.services.mumble.loadbalancer.server.port=64738
      - traefik.tcp.routers.mumble.entrypoints=mumble_tcp
      - traefik.tcp.routers.mumble.service=mumble
      - traefik.tcp.routers.mumble.rule=HostSNI(`mumble.black-rose.space`)
      - traefik.tcp.services.mumble.loadbalancer.server.port=64738
      - traefik.tcp.routers.mumble.tls.passthrough=true

  redis:
    image: redis:6.2
    command: redis-server
    restart: always
    volumes:
      - "redis-data:/data"
    networks:
      - allianceauth

  allianceauth:
    build:
      context: .
      dockerfile: auth.dockerfile
      args:
        AA_DOCKER_TAG: ${AA_DOCKER_TAG?err}
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./conf/local.py:/home/allianceauth/myauth/myauth/settings/local.py
      - ./templates:/home/allianceauth/myauth/myauth/templates/
      - ./conf/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - static-volume:/var/www/myauth/static
    depends_on:
      - redis
      - auth_mysql
      - mumble_auth
    networks:
      - allianceauth

volumes:
    redis-data:
    static-volume:
    mumble-data:

networks:
  allianceauth:
  traefik:
    external: true
